/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicInfo: typeof import('./src/components/detail/BasicInfo.vue')['default']
    FixtureCard: typeof import('./src/components/FixtureCard.vue')['default']
    FixtureList: typeof import('./src/components/FixtureList.vue')['default']
    H2HTab: typeof import('./src/components/detail/H2HTab.vue')['default']
    LeagueMenu: typeof import('./src/components/LeagueMenu.vue')['default']
    LineupTab: typeof import('./src/components/detail/LineupTab.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NH4: typeof import('naive-ui')['NH4']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLi: typeof import('naive-ui')['NLi']
    NMenu: typeof import('naive-ui')['NMenu']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NProgress: typeof import('naive-ui')['NProgress']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NTable: typeof import('naive-ui')['NTable']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NUl: typeof import('naive-ui')['NUl']
    OpinionInput: typeof import('./src/components/detail/OpinionInput.vue')['default']
    PredictionResult: typeof import('./src/components/detail/PredictionResult.vue')['default']
    PredictionTab: typeof import('./src/components/detail/PredictionTab.vue')['default']
    ProbabilityChart: typeof import('./src/components/ProbabilityChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsTab: typeof import('./src/components/detail/StatsTab.vue')['default']
    TabsContainer: typeof import('./src/components/detail/TabsContainer.vue')['default']
  }
}
