"""API-Sports team id / English name → 中文 display name.

Single source of truth for club/national-team display names:
- applied on ingest (``FootballFetcher._upsert_team``)
- backfilled across ``teams`` after sync
- applied when summarizing / serving H2H & form packages

Naming style: short English keys / common IDs use fan-facing short Chinese
(e.g. Bayern→拜仁, PSG→巴黎); fuller official English keeps fuller Chinese
(e.g. Bayern Munich→拜仁慕尼黑). Multiple keys for one club are intentional aliases.

Unmapped names stay as the official string.
"""

from __future__ import annotations

from typing import Any

# Prefer stable API-Sports team ids.
BY_ID: dict[int, str] = {
    # National teams
    1: "比利时",
    2: "法国",
    3: "克罗地亚",
    5: "瑞典",
    6: "巴西",
    7: "乌拉圭",
    8: "哥伦比亚",
    9: "西班牙",
    10: "英格兰",
    11: "巴拿马",
    12: "日本",
    13: "塞内加尔",
    15: "瑞士",
    16: "墨西哥",
    17: "韩国",
    20: "澳大利亚",
    22: "伊朗",
    23: "沙特阿拉伯",
    25: "德国",
    26: "阿根廷",
    27: "葡萄牙",
    28: "突尼斯",
    31: "摩洛哥",
    32: "埃及",
    770: "捷克",
    775: "奥地利",
    777: "土耳其",
    1090: "挪威",
    1108: "苏格兰",
    1113: "波黑",
    1118: "荷兰",
    1501: "科特迪瓦",
    1504: "加纳",
    1506: "埃塞俄比亚",
    1508: "刚果（金）",
    1531: "南非",
    1532: "阿尔及利亚",
    1533: "佛得角",
    1542: "越南",
    1548: "约旦",
    1567: "伊拉克",
    1568: "乌兹别克斯坦",
    1569: "卡塔尔",
    2380: "巴拉圭",
    2382: "厄瓜多尔",
    2384: "美国",
    2386: "海地",
    4673: "新西兰",
    5529: "加拿大",
    5530: "库拉索",
    # —— 五大联赛（API-Sports 稳定 team id）——
    # 英超
    33: "曼联",
    34: "纽卡斯尔",
    35: "伯恩茅斯",
    36: "富勒姆",
    39: "狼队",
    40: "利物浦",
    41: "南安普顿",
    42: "阿森纳",
    44: "伯恩利",
    45: "埃弗顿",
    46: "莱斯特城",
    47: "热刺",
    48: "西汉姆联",
    49: "切尔西",
    50: "曼城",
    51: "布莱顿",
    52: "水晶宫",
    55: "布伦特福德",
    57: "伊普斯维奇",
    63: "利兹联",
    65: "诺丁汉森林",
    66: "阿斯顿维拉",
    71: "诺维奇",
    746: "桑德兰",
    # 西甲
    529: "巴萨",
    530: "马竞",
    531: "毕尔巴鄂",
    532: "瓦伦西亚",
    533: "维拉利尔",
    536: "塞维利亚",
    538: "塞尔塔",
    540: "西班牙人",
    541: "皇马",
    542: "阿拉维斯",
    543: "贝蒂斯",
    546: "赫塔费",
    547: "赫罗纳",
    548: "皇家社会",
    715: "格拉纳达",
    720: "巴拉多利德",
    724: "加的斯",
    726: "莱加内斯",
    727: "奥萨苏纳",
    728: "巴列卡诺",
    797: "埃尔切",
    798: "马略卡",
    750: "拉斯帕尔马斯",
    9580: "莱万特",
    # 德甲
    157: "拜仁",
    159: "柏林赫塔",
    160: "弗赖堡",
    161: "沃尔夫斯堡",
    162: "云达不莱梅",
    163: "门兴",
    164: "美因茨",
    165: "多特",
    167: "霍芬海姆",
    168: "勒沃库森",
    169: "法兰克福",
    170: "奥格斯堡",
    172: "斯图加特",
    173: "莱比锡",
    174: "沙尔克04",
    175: "达姆施塔特",
    178: "波鸿",
    182: "柏林联合",
    186: "科隆",
    191: "海登海姆",
    192: "圣保利",
    761: "霍尔施泰因基尔",
    # 意甲
    487: "拉齐奥",
    488: "萨索洛",
    489: "AC米兰",
    490: "卡利亚里",
    492: "那不勒斯",
    494: "乌迪内斯",
    495: "热那亚",
    496: "尤文",
    497: "罗马",
    498: "桑普多利亚",
    499: "亚特兰大",
    500: "博洛尼亚",
    502: "佛罗伦萨",
    503: "都灵",
    504: "维罗纳",
    505: "国米",
    511: "恩波利",
    512: "弗洛西诺内",
    515: "斯佩齐亚",
    517: "威尼斯",
    523: "帕尔马",
    801: "科莫",
    867: "莱切",
    895: "克雷莫纳",
    1579: "蒙扎",
    # 法甲
    77: "昂热",
    79: "里尔",
    80: "里昂",
    81: "马赛",
    82: "蒙彼利埃",
    83: "南特",
    84: "尼斯",
    85: "巴黎",
    91: "摩纳哥",
    93: "雷恩",
    95: "斯特拉斯堡",
    96: "图卢兹",
    97: "洛里昂",
    99: "兰斯",
    106: "圣埃蒂安",
    108: "欧塞尔",
    111: "勒阿弗尔",
    112: "梅斯",
    116: "朗斯",
    129: "布雷斯特",
    130: "克莱蒙",
    1063: "巴黎FC",
    # Europe cups / smaller leagues
    275: "斯特亚尔南",
    278: "雷克雅未克维京人",
    354: "新圣徒",
    356: "卡那封镇",
    357: "康纳斯码头",
    388: "鲍里索夫BATE",
    394: "明斯克迪纳摩",
    556: "卡拉巴赫",
    562: "阿斯塔纳",
    568: "蒂拉斯波尔警长",
    572: "基辅迪纳摩",
    574: "斯科普里瓦尔达尔",
    580: "戈塔维京人",
    582: "阿拉什克特",
    583: "林菲尔德",
    586: "维尔纽斯扎尔吉里斯",
    591: "圣科洛马",
    608: "斯普利特海杜克",
    609: "什肯迪亚",
    632: "克拉约瓦大学",
    646: "索菲亚列夫斯基",
    648: "齐拉",
    651: "费伦茨瓦罗斯",
    652: "沙姆洛克流浪",
    661: "利耶帕亚",
    662: "诺姆卡柳",
    664: "阿拉木图凯拉特",
    667: "林肯红魔鬼",
    670: "德里城",
    673: "苏捷斯卡",
    679: "萨拉热窝",
    682: "鲁纳维克",
    684: "迪弗当日",
    685: "库塔伊西鱼雷",
    687: "塔林弗洛拉",
    691: "奥尔黑米勒萨米",
    698: "圣约瑟夫",
    701: "克拉克斯维克",
    702: "伏伊伏丁那",
    709: "埃里温皮尤尼克",
    853: "索菲亚中央陆军",
    1163: "伊尔维斯",
    1164: "图尔库国际",
    1165: "库普斯",
    1615: "华盛顿联",
    2036: "UNA斯特拉森",
    2037: "蒙多夫",
    2191: "佩尼邦特",
    2249: "拉菲奥里塔",
    2260: "特雷菲奥里",
    2262: "第比利斯迪纳摩",
    2271: "彼得罗库布",
    2273: "塔林列瓦迪亚",
    2402: "吉奥利ETO",
    2599: "克卢日大学",
    3326: "地拉那迪纳摩",
    3327: "罗戈日纳埃格纳蒂亚",
    3339: "斯库台弗拉兹尼亚",
    3345: "埃斯卡尔德斯竞技",
    3364: "巴尼亚卢卡博拉茨",
    3381: "韦莱日",
    3499: "迪拉",
    3502: "萨布尔塔洛",
    3528: "派德",
    3554: "日利纳",
    3683: "阿拉拉特亚美尼亚",
    3740: "莫尔纳尔",
    3741: "彼得罗瓦茨",
    3745: "德契奇",
    3840: "波希米亚人",
    3861: "黑格尔曼",
    3872: "考纳斯扎尔吉里斯",
    4160: "里加FS",
    4165: "韦斯特里",
    4331: "西莱克斯",
    4358: "阿卢米尼",
    4625: "弗洛里亚纳",
    4626: "哈姆伦斯巴达",
    5308: "维尔图斯",
    5352: "格伦托兰",
    5354: "拉恩",
    7808: "维捷布斯克ML",
    10124: "里加",
    10125: "欧罗巴",
    12733: "巴尔卡尼",
    13976: "沙巴赫",
    14281: "德里塔",
    14507: "马尔萨什洛克",
    15576: "马利舍瓦",
    15847: "阿泰特比森",
    18762: "利伯塔德",
    20406: "爱尔巴桑尼",
    21011: "塞梅伊叶利迈",
    # 中超 / 中国
    830: "北京国安",
    833: "上海申花",
    834: "长春亚泰",
    836: "上海海港",
    837: "天津津门虎",
    838: "大连人",
    840: "河南",
    843: "广州",
    844: "山东泰山",
    848: "浙江",
    1431: "青岛海牛",
    5648: "成都蓉城",
    5684: "辽宁铁人",
    5686: "深圳新鹏城",
    5695: "武汉三镇",
    8351: "沧州雄狮",
    15784: "南通支云",
    17265: "青岛西海岸",
    21262: "重庆铜梁龙",
    21263: "大连英博",
    21265: "云南玉昆",
    # 中协杯 / 中甲 / 中乙（2026 足协杯）
    21328: "兰州陇原竞技",
    23286: "陕西联合",
    27620: "大连可为",
    # 韩K联
    2745: "富川1995",
    2746: "江原FC",
    2748: "安养FC",
    2750: "大田市民",
    2759: "光州FC",
    2761: "济州联",
    2762: "全北现代",
    2763: "仁川联",
    2764: "浦项制铁",
    2766: "首尔FC",
    2767: "蔚山HD",
    2768: "金泉尚武",
    # 厄甲
    1148: "埃梅莱克",
    1149: "德尔芬",
    1151: "技术大学",
    1152: "瓜亚基尔巴塞罗那",
    1153: "独立山谷",
    1154: "昆卡体育",
    1155: "马卡拉",
    1156: "奥卡斯",
    1157: "天主教大学",
    1158: "基多大学",
    1159: "瓜亚基尔城",
    1162: "穆舒克鲁纳",
    1980: "曼塔FC",
    1992: "奥伦塞",
    19034: "北部雄狮",
    # Youth / U17 / U20
    12501: "澳大利亚U17",
    12516: "尼日利亚U17",
    19624: "巴林U20",
    19629: "阿曼U20",
    19630: "巴勒斯坦U20",
    21060: "塔吉克斯坦U20",
    21449: "中国U17",
    25822: "坦桑尼亚U17",
}

_BY_NAME_RAW: dict[str, str] = {
    "Belgium": "比利时",
    "France": "法国",
    "Croatia": "克罗地亚",
    "Sweden": "瑞典",
    "Brazil": "巴西",
    "Uruguay": "乌拉圭",
    "Colombia": "哥伦比亚",
    "Spain": "西班牙",
    "England": "英格兰",
    "Panama": "巴拿马",
    "Japan": "日本",
    "Senegal": "塞内加尔",
    "Switzerland": "瑞士",
    "Mexico": "墨西哥",
    "South Korea": "韩国",
    "Australia": "澳大利亚",
    "Iran": "伊朗",
    "Saudi Arabia": "沙特阿拉伯",
    "Germany": "德国",
    "Argentina": "阿根廷",
    "Portugal": "葡萄牙",
    "Tunisia": "突尼斯",
    "Morocco": "摩洛哥",
    "Egypt": "埃及",
    "Czechia": "捷克",
    "Czech Republic": "捷克",
    "Austria": "奥地利",
    "Türkiye": "土耳其",
    "Turkey": "土耳其",
    "Norway": "挪威",
    "Scotland": "苏格兰",
    "Bosnia & Herzegovina": "波黑",
    "Bosnia and Herzegovina": "波黑",
    "Netherlands": "荷兰",
    "Ivory Coast": "科特迪瓦",
    "Côte d'Ivoire": "科特迪瓦",
    "Ghana": "加纳",
    "Ethiopia": "埃塞俄比亚",
    "Congo DR": "刚果（金）",
    "DR Congo": "刚果（金）",
    "South Africa": "南非",
    "Algeria": "阿尔及利亚",
    "Cape Verde Islands": "佛得角",
    "Cape Verde": "佛得角",
    "Vietnam": "越南",
    "Jordan": "约旦",
    "Iraq": "伊拉克",
    "Uzbekistan": "乌兹别克斯坦",
    "Qatar": "卡塔尔",
    "Paraguay": "巴拉圭",
    "Ecuador": "厄瓜多尔",
    "USA": "美国",
    "United States": "美国",
    "Haiti": "海地",
    "New Zealand": "新西兰",
    "Canada": "加拿大",
    "Curaçao": "库拉索",
    "Curacao": "库拉索",
    "Stjarnan": "斯特亚尔南",
    "Vikingur Reykjavik": "雷克雅未克维京人",
    "The New Saints": "新圣徒",
    "Caernarfon Town": "卡那封镇",
    "GAP Connah S Quay FC": "康纳斯码头",
    "Connah's Quay": "康纳斯码头",
    "Bate Borisov": "鲍里索夫BATE",
    "BATE Borisov": "鲍里索夫BATE",
    "Dinamo Minsk": "明斯克迪纳摩",
    "Qarabag": "卡拉巴赫",
    "FC Astana": "阿斯塔纳",
    "Sheriff Tiraspol": "蒂拉斯波尔警长",
    "Dynamo Kyiv": "基辅迪纳摩",
    "Vardar Skopje": "斯科普里瓦尔达尔",
    "Vikingur Gota": "戈塔维京人",
    "Alashkert": "阿拉什克特",
    "Linfield": "林菲尔德",
    "FK Zalgiris Vilnius": "维尔纽斯扎尔吉里斯",
    "FC Santa Coloma": "圣科洛马",
    "HNK Hajduk Split": "斯普利特海杜克",
    "Shkendija": "什肯迪亚",
    "Universitatea Craiova": "克拉约瓦大学",
    "Levski Sofia": "索菲亚列夫斯基",
    "Zira": "齐拉",
    "Ferencvarosi TC": "费伦茨瓦罗斯",
    "Shamrock Rovers": "沙姆洛克流浪",
    "FK Liepaja": "利耶帕亚",
    "Kalju Nomme": "诺姆卡柳",
    "Kairat Almaty": "阿拉木图凯拉特",
    "Lincoln Red Imps FC": "林肯红魔鬼",
    "Derry City": "德里城",
    "Sutjeska": "苏捷斯卡",
    "FK Sarajevo": "萨拉热窝",
    "NSI Runavik": "鲁纳维克",
    "FC Differdange 03": "迪弗当日",
    "Torpedo Kutaisi": "库塔伊西鱼雷",
    "Flora Tallinn": "塔林弗洛拉",
    "Milsami Orhei": "奥尔黑米勒萨米",
    "St Joseph S Fc": "圣约瑟夫",
    "KI Klaksvik": "克拉克斯维克",
    "Vojvodina": "伏伊伏丁那",
    "Pyunik Yerevan": "埃里温皮尤尼克",
    "CSKA Sofia": "索菲亚中央陆军",
    "Ilves": "伊尔维斯",
    "Inter Turku": "图尔库国际",
    "KuPS": "库普斯",
    "DC United": "华盛顿联",
    "UNA Strassen": "UNA斯特拉森",
    "US Mondorf-les-bains": "蒙多夫",
    "Penybont": "佩尼邦特",
    "La Fiorita": "拉菲奥里塔",
    "Tre Fiori": "特雷菲奥里",
    "Dinamo Tbilisi": "第比利斯迪纳摩",
    "Petrocub": "彼得罗库布",
    "FC Levadia Tallinn": "塔林列瓦迪亚",
    "Gyori ETO FC": "吉奥利ETO",
    "Universitatea Cluj": "克卢日大学",
    "Dinamo Tirana": "地拉那迪纳摩",
    "Egnatia Rrogozhinë": "罗戈日纳埃格纳蒂亚",
    "Egnatia": "罗戈日纳埃格纳蒂亚",
    "Vllaznia Shkodër": "斯库台弗拉兹尼亚",
    "Atlètic Club d'Escaldes": "埃斯卡尔德斯竞技",
    "Atletic Club d'Escaldes": "埃斯卡尔德斯竞技",
    "Borac Banja Luka": "巴尼亚卢卡博拉茨",
    "Velež": "韦莱日",
    "Dila": "迪拉",
    "Saburtalo": "萨布尔塔洛",
    "Paide": "派德",
    "Žilina": "日利纳",
    "Zilina": "日利纳",
    "Ararat-Armenia": "阿拉拉特亚美尼亚",
    "Mornar": "莫尔纳尔",
    "Petrovac": "彼得罗瓦茨",
    "Dečić": "德契奇",
    "Bohemians": "波希米亚人",
    "Hegelmann Litauen": "黑格尔曼",
    "Kauno Žalgiris": "考纳斯扎尔吉里斯",
    "Kauno Zalgiris": "考纳斯扎尔吉里斯",
    "Rīgas FS": "里加FS",
    "Vestri": "韦斯特里",
    "Sileks": "西莱克斯",
    "Aluminij": "阿卢米尼",
    "Floriana": "弗洛里亚纳",
    "Hamrun Spartans": "哈姆伦斯巴达",
    "Virtus": "维尔图斯",
    "Glentoran": "格伦托兰",
    "Larne": "拉恩",
    "ML Vitebsk": "维捷布斯克ML",
    "Riga": "里加",
    "Europa": "欧罗巴",
    "Ballkani": "巴尔卡尼",
    "Sabah FA": "沙巴赫",
    "Drita": "德里塔",
    "Marsaxlokk": "马尔萨什洛克",
    "Malisheva": "马利舍瓦",
    "Atert Bissen": "阿泰特比森",
    "Libertad": "利伯塔德",
    "AF Elbasani": "爱尔巴桑尼",
    "Yelimay Semey": "塞梅伊叶利迈",
    # 英超
    "Manchester City": "曼城",
    "Manchester United": "曼联",
    "Liverpool": "利物浦",
    "Arsenal": "阿森纳",
    "Chelsea": "切尔西",
    "Tottenham": "热刺",
    "Tottenham Hotspur": "热刺",
    "Newcastle": "纽卡斯尔",
    "Newcastle United": "纽卡斯尔",
    "Aston Villa": "阿斯顿维拉",
    "West Ham": "西汉姆联",
    "West Ham United": "西汉姆联",
    "Brighton": "布莱顿",
    "Brighton and Hove Albion": "布莱顿",
    "Crystal Palace": "水晶宫",
    "Everton": "埃弗顿",
    "Fulham": "富勒姆",
    "Brentford": "布伦特福德",
    "Bournemouth": "伯恩茅斯",
    "Wolves": "狼队",
    "Wolverhampton Wanderers": "狼队",
    "Nottingham Forest": "诺丁汉森林",
    "Leicester": "莱斯特城",
    "Leicester City": "莱斯特城",
    "Southampton": "南安普顿",
    "Ipswich": "伊普斯维奇",
    "Ipswich Town": "伊普斯维奇",
    "Leeds": "利兹联",
    "Leeds United": "利兹联",
    "Burnley": "伯恩利",
    "Sunderland": "桑德兰",
    # 西甲（短 key → 球迷简称；全称 key → 全称）
    "Barcelona": "巴萨",
    "FC Barcelona": "巴塞罗那",
    "Barca": "巴萨",
    "Real Madrid": "皇马",
    "Real Madrid CF": "皇家马德里",
    "Atletico Madrid": "马竞",
    "Atlético Madrid": "马竞",
    "Atleti": "马竞",
    "Athletic Club": "毕尔巴鄂",
    "Athletic Bilbao": "毕尔巴鄂",
    "Real Sociedad": "皇家社会",
    "Real Betis": "贝蒂斯",
    "Villarreal": "维拉利尔",
    "Sevilla": "塞维利亚",
    "Valencia": "瓦伦西亚",
    "Girona": "赫罗纳",
    "Osasuna": "奥萨苏纳",
    "Celta": "塞尔塔",
    "Celta Vigo": "塞尔塔",
    "Rayo Vallecano": "巴列卡诺",
    "Mallorca": "马略卡",
    "Getafe": "赫塔费",
    "Espanyol": "西班牙人",
    "Alaves": "阿拉维斯",
    "Deportivo Alaves": "阿拉维斯",
    "Leganes": "莱加内斯",
    "Las Palmas": "拉斯帕尔马斯",
    "Valladolid": "巴拉多利德",
    "Cadiz": "加的斯",
    "Granada CF": "格拉纳达",
    "Elche": "埃尔切",
    "Levante": "莱万特",
    # 德甲
    "Bayern": "拜仁",
    "Bayern Munich": "拜仁慕尼黑",
    "Bayern München": "拜仁慕尼黑",
    "Dortmund": "多特",
    "Borussia Dortmund": "多特蒙德",
    "Leipzig": "莱比锡",
    "RB Leipzig": "莱比锡红牛",
    "Leverkusen": "勒沃库森",
    "Bayer Leverkusen": "勒沃库森",
    "Frankfurt": "法兰克福",
    "Eintracht Frankfurt": "法兰克福",
    "Stuttgart": "斯图加特",
    "VfB Stuttgart": "斯图加特",
    "Gladbach": "门兴",
    "Borussia Monchengladbach": "门兴格拉德巴赫",
    "Borussia M.Gladbach": "门兴格拉德巴赫",
    "Wolfsburg": "沃尔夫斯堡",
    "Freiburg": "弗赖堡",
    "SC Freiburg": "弗赖堡",
    "Hoffenheim": "霍芬海姆",
    "Augsburg": "奥格斯堡",
    "FC Augsburg": "奥格斯堡",
    "Mainz": "美因茨",
    "Mainz 05": "美因茨",
    "FSV Mainz 05": "美因茨",
    "Union Berlin": "柏林联合",
    "Bremen": "不莱梅",
    "Werder Bremen": "云达不莱梅",
    "Koln": "科隆",
    "FC Koln": "科隆",
    "1.FC Köln": "科隆",
    "Bochum": "波鸿",
    "Heidenheim": "海登海姆",
    "St. Pauli": "圣保利",
    "Holstein Kiel": "霍尔施泰因基尔",
    "Hertha": "赫塔",
    "Hertha Berlin": "柏林赫塔",
    "Schalke": "沙尔克",
    "Schalke 04": "沙尔克04",
    # 意甲
    "Inter": "国米",
    "Inter Milan": "国际米兰",
    "Milan": "AC米兰",
    "AC Milan": "AC米兰",
    "Juve": "尤文",
    "Juventus": "尤文",
    "Napoli": "那不勒斯",
    "AS Roma": "罗马",
    "Roma": "罗马",
    "Lazio": "拉齐奥",
    "Atalanta": "亚特兰大",
    "Fiorentina": "佛罗伦萨",
    "Bologna": "博洛尼亚",
    "Torino": "都灵",
    "Udinese": "乌迪内斯",
    "Genoa": "热那亚",
    "Cagliari": "卡利亚里",
    "Lecce": "莱切",
    "Empoli": "恩波利",
    "Verona": "维罗纳",
    "Hellas Verona": "维罗纳",
    "Monza": "蒙扎",
    "Sassuolo": "萨索洛",
    "Parma": "帕尔马",
    "Como": "科莫",
    "Venezia": "威尼斯",
    "Cremonese": "克雷莫纳",
    # 法甲
    "PSG": "巴黎",
    "Paris": "巴黎",
    "Paris Saint Germain": "巴黎圣日耳曼",
    "Paris Saint-Germain": "巴黎圣日耳曼",
    "Marseille": "马赛",
    "Olympique Marseille": "马赛",
    "OM": "马赛",
    "Monaco": "摩纳哥",
    "Lyon": "里昂",
    "Olympique Lyonnais": "里昂",
    "OL": "里昂",
    "Lille": "里尔",
    "Nice": "尼斯",
    "Rennes": "雷恩",
    "Lens": "朗斯",
    "Strasbourg": "斯特拉斯堡",
    "Nantes": "南特",
    "Toulouse": "图卢兹",
    "Brest": "布雷斯特",
    "Reims": "兰斯",
    "Montpellier": "蒙彼利埃",
    "Le Havre": "勒阿弗尔",
    "Angers": "昂热",
    "Auxerre": "欧塞尔",
    "Saint Etienne": "圣埃蒂安",
    "Saint-Etienne": "圣埃蒂安",
    "Metz": "梅斯",
    "Lorient": "洛里昂",
    "Clermont Foot": "克莱蒙",
    "Paris FC": "巴黎FC",
    # 其它常见英文名
    "Ipswich Town FC": "伊普斯维奇",
    "Inter Club d'Escaldes": "埃斯卡尔德斯国际",
    "F91 Dudelange": "迪德朗日",
    "Penya Encarnada": "佩尼亚恩卡纳达",
    "Pas de la Casa": "帕斯德拉卡萨",
    "La Massana": "拉马萨纳",
    "Shandong Luneng": "山东泰山",
    "Shandong Taishan": "山东泰山",
    "Yunnan Yukun": "云南玉昆",
    "Beijing Guoan": "北京国安",
    "Shanghai Shenhua": "上海申花",
    "Shanghai Port": "上海海港",
    "Shanghai SIPG": "上海海港",
    "Henan Jianye": "河南",
    "Henan Songshan Longmen": "河南",
    "Hangzhou Greentown": "浙江",
    "Zhejiang Professional": "浙江",
    "Zhejiang": "浙江",
    "Wuhan Three Towns": "武汉三镇",
    "Chengdu Better City": "成都蓉城",
    "Chengdu Rongcheng": "成都蓉城",
    "Sichuan Jiuniu": "深圳新鹏城",
    "Shenzhen Xinpengcheng": "深圳新鹏城",
    "Qingdao Jonoon": "青岛海牛",
    "Qingdao Hainiu": "青岛海牛",
    "Qingdao Youth Island": "青岛西海岸",
    "Qingdao West Coast": "青岛西海岸",
    "Chongqing Tongliang Long": "重庆铜梁龙",
    "Tianjin Teda": "天津津门虎",
    "Tianjin Jinmen Tiger": "天津津门虎",
    "Changchun Yatai": "长春亚泰",
    "Meizhou Hakka": "梅州客家",
    "Cangzhou Mighty Lions": "沧州雄狮",
    "Nantong Zhiyun": "南通支云",
    "Shenyang Urban": "辽宁铁人",
    "Dalian Zhixing": "大连英博",
    "Rizhao Yuqi": "兰州陇原竞技",
    "Lanzhou Longyuan Athletic": "兰州陇原竞技",
    "Lanzhou Longyuan": "兰州陇原竞技",
    "Shaanxi Union": "陕西联合",
    "Dalian Kewei": "大连可为",
    "Bucheon FC 1995": "富川1995",
    "Gangwon FC": "江原FC",
    "FC Anyang": "安养FC",
    "Daejeon Citizen": "大田市民",
    "Gwangju FC": "光州FC",
    "Jeju United FC": "济州联",
    "Jeonbuk Motors": "全北现代",
    "Incheon United": "仁川联",
    "Pohang Steelers": "浦项制铁",
    "FC Seoul": "首尔FC",
    "Ulsan Hyundai FC": "蔚山HD",
    "Gimcheon Sangmu FC": "金泉尚武",
    "Emelec": "埃梅莱克",
    "Delfin SC": "德尔芬",
    "Tecnico Universitario": "技术大学",
    "Barcelona SC": "瓜亚基尔巴塞罗那",
    "Independiente del Valle": "独立山谷",
    "Deportivo Cuenca": "昆卡体育",
    "Macara": "马卡拉",
    "Aucas": "奥卡斯",
    "Universidad Catolica": "天主教大学",
    "LDU de Quito": "基多大学",
    "Guayaquil City FC": "瓜亚基尔城",
    "Mushuc Runa SC": "穆舒克鲁纳",
    "Manta FC": "曼塔FC",
    "Orense SC": "奥伦塞",
    "Leones del Norte": "北部雄狮",
    "Australia U17": "澳大利亚U17",
    "Nigeria U17": "尼日利亚U17",
    "Bahrain U20": "巴林U20",
    "Oman U20": "阿曼U20",
    "Palestine U20": "巴勒斯坦U20",
    "Tajikistan U20": "塔吉克斯坦U20",
    "China PR U17": "中国U17",
    "Tanzania U17": "坦桑尼亚U17",
}

BY_NAME: dict[str, str] = {k.lower(): v for k, v in _BY_NAME_RAW.items()}


def team_name_zh(name: str | None, team_id: int | None = None) -> str:
    """Resolve Chinese display name; fall back to original / empty."""
    if team_id is not None:
        try:
            tid = int(team_id)
        except (TypeError, ValueError):
            tid = None
        if tid is not None and tid in BY_ID:
            return BY_ID[tid]
    if not name:
        return ""
    trimmed = str(name).strip()
    hit = BY_NAME.get(trimmed.lower())
    if hit:
        return hit
    return trimmed


def localize_match_teams(match: dict[str, Any]) -> dict[str, Any]:
    """Rewrite home/away labels on a form/H2H match row (in place + return)."""
    home_id = match.get("home_id")
    away_id = match.get("away_id")
    try:
        hid = int(home_id) if home_id is not None else None
    except (TypeError, ValueError):
        hid = None
    try:
        aid = int(away_id) if away_id is not None else None
    except (TypeError, ValueError):
        aid = None
    home = match.get("home")
    away = match.get("away")
    if home is not None or hid is not None:
        match["home"] = team_name_zh(home if isinstance(home, str) else None, hid) or home
    if away is not None or aid is not None:
        match["away"] = team_name_zh(away if isinstance(away, str) else None, aid) or away
    return match


async def backfill_team_names(session: Any) -> int:
    """Rewrite ``teams.name`` for every row that has a Chinese mapping.

    Returns the number of rows changed. Call after fixture sync so historical
    English rows become reusable Chinese names without waiting for re-fetch.
    """
    from sqlalchemy import select

    from app.models.team import Team

    rows = (await session.execute(select(Team))).scalars().all()
    updated = 0
    for team in rows:
        zh = team_name_zh(team.name, team.id)
        if zh and zh != team.name:
            team.name = zh
            updated += 1
    if updated:
        await session.commit()
    return updated
