"""API-Sports team id / English name → 中文 display name.

Single source of truth for club/national-team display names:
- applied on ingest (``FootballFetcher._upsert_team``)
- backfilled across ``teams`` after sync
- applied when summarizing / serving H2H & form packages

Naming style: short English keys / common IDs use fan-facing short Chinese
(e.g. Bayern→拜仁, PSG→巴黎); fuller official English keeps fuller Chinese
(e.g. Bayern Munich→拜仁慕尼黑). Multiple keys for one club are intentional aliases.

``BY_ID`` / ``_BY_NAME_RAW`` are grouped by competition (五大联赛 → 二级联赛 →
亚欧美 → 欧陆其他), with ids sorted inside each group. Prefer adding new
entries under the matching league comment — not under date-based dumps.

Unmapped names stay as the official string.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Runtime auto-translations for catalog-league clubs (curated BY_ID always wins).
_DATA_DIR = Path(__file__).resolve().parents[2] / "data"
AUTO_NAMES_PATH = _DATA_DIR / "team_names_auto.json"


def _load_auto_by_id() -> dict[int, str]:
    if not AUTO_NAMES_PATH.is_file():
        return {}
    try:
        raw = json.loads(AUTO_NAMES_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        logger.warning("Failed to load %s: %s", AUTO_NAMES_PATH, exc)
        return {}
    if not isinstance(raw, dict):
        return {}
    out: dict[int, str] = {}
    for key, value in raw.items():
        try:
            tid = int(key)
        except (TypeError, ValueError):
            continue
        text = str(value or "").strip()
        if tid > 0 and text:
            out[tid] = text
    return out


AUTO_BY_ID: dict[int, str] = _load_auto_by_id()

# Prefer stable API-Sports team ids.
BY_ID: dict[int, str] = {
    # 国家队
    1: "比利时",
    2: "法国",
    3: "克罗地亚",
    5: "瑞典",
    6: "巴西",
    7: "乌拉圭",
    8: "哥伦比亚",
    9: "西班牙",
    10: "英格兰",
    11: "巴拿马",
    12: "日本",
    13: "塞内加尔",
    15: "瑞士",
    16: "墨西哥",
    17: "韩国",
    20: "澳大利亚",
    22: "伊朗",
    23: "沙特阿拉伯",
    25: "德国",
    26: "阿根廷",
    27: "葡萄牙",
    28: "突尼斯",
    31: "摩洛哥",
    32: "埃及",
    770: "捷克",
    775: "奥地利",
    777: "土耳其",
    1090: "挪威",
    1108: "苏格兰",
    1113: "波黑",
    1118: "荷兰",
    1501: "科特迪瓦",
    1504: "加纳",
    1506: "埃塞俄比亚",
    1508: "刚果（金）",
    1531: "南非",
    1532: "阿尔及利亚",
    1533: "佛得角",
    1542: "越南",
    1548: "约旦",
    1567: "伊拉克",
    1568: "乌兹别克斯坦",
    1569: "卡塔尔",
    2380: "巴拉圭",
    2382: "厄瓜多尔",
    2384: "美国",
    2386: "海地",
    4673: "新西兰",
    5529: "加拿大",
    5530: "库拉索",
    # 英超
    33: "曼联",
    34: "纽卡斯尔",
    35: "伯恩茅斯",
    36: "富勒姆",
    39: "狼队",
    40: "利物浦",
    41: "南安普顿",
    42: "阿森纳",
    44: "伯恩利",
    45: "埃弗顿",
    46: "莱斯特城",
    47: "热刺",
    48: "西汉姆联",
    49: "切尔西",
    50: "曼城",
    51: "布莱顿",
    52: "水晶宫",
    55: "布伦特福德",
    57: "伊普斯维奇",
    63: "利兹联",
    65: "诺丁汉森林",
    66: "阿斯顿维拉",
    71: "诺维奇",
    746: "桑德兰",
    # 西甲
    529: "巴萨",
    530: "马竞",
    531: "毕尔巴鄂",
    532: "瓦伦西亚",
    533: "维拉利尔",
    536: "塞维利亚",
    538: "塞尔塔",
    540: "西班牙人",
    541: "皇马",
    542: "阿拉维斯",
    543: "贝蒂斯",
    546: "赫塔费",
    547: "赫罗纳",
    548: "皇家社会",
    715: "格拉纳达",
    720: "巴拉多利德",
    724: "加的斯",
    726: "莱加内斯",
    727: "奥萨苏纳",
    728: "巴列卡诺",
    750: "拉斯帕尔马斯",
    797: "埃尔切",
    798: "马略卡",
    9580: "莱万特",
    # 德甲
    157: "拜仁",
    159: "柏林赫塔",
    160: "弗赖堡",
    161: "沃尔夫斯堡",
    162: "云达不莱梅",
    163: "门兴",
    164: "美因茨",
    165: "多特",
    167: "霍芬海姆",
    168: "勒沃库森",
    169: "法兰克福",
    170: "奥格斯堡",
    172: "斯图加特",
    173: "莱比锡",
    174: "沙尔克04",
    175: "达姆施塔特",
    178: "波鸿",
    182: "柏林联合",
    186: "科隆",
    191: "海登海姆",
    192: "圣保利",
    761: "霍尔施泰因基尔",
    # 意甲
    487: "拉齐奥",
    488: "萨索洛",
    489: "AC米兰",
    490: "卡利亚里",
    492: "那不勒斯",
    494: "乌迪内斯",
    495: "热那亚",
    496: "尤文",
    497: "罗马",
    498: "桑普多利亚",
    499: "亚特兰大",
    500: "博洛尼亚",
    502: "佛罗伦萨",
    503: "都灵",
    504: "维罗纳",
    505: "国米",
    511: "恩波利",
    512: "弗洛西诺内",
    515: "斯佩齐亚",
    517: "威尼斯",
    523: "帕尔马",
    801: "科莫",
    867: "莱切",
    895: "克雷莫纳",
    1579: "蒙扎",
    # 法甲
    77: "昂热",
    79: "里尔",
    80: "里昂",
    81: "马赛",
    82: "蒙彼利埃",
    83: "南特",
    84: "尼斯",
    85: "巴黎",
    91: "摩纳哥",
    93: "雷恩",
    95: "斯特拉斯堡",
    96: "图卢兹",
    97: "洛里昂",
    99: "兰斯",
    106: "圣埃蒂安",
    108: "欧塞尔",
    111: "勒阿弗尔",
    112: "梅斯",
    116: "朗斯",
    129: "布雷斯特",
    130: "克莱蒙",
    1063: "巴黎FC",
    # 德乙
    166: "汉诺威96",
    171: "纽伦堡",
    176: "波鸿",
    179: "马格德堡",
    180: "海登海姆",
    181: "达姆施塔特",
    183: "德累斯顿迪纳摩",
    188: "比勒费尔德",
    744: "不伦瑞克",
    745: "凯泽斯劳滕",
    785: "卡尔斯鲁厄",
    1320: "科特布斯能量",
    1324: "奥斯纳布吕克",
    # 法乙
    89: "第戎",
    90: "甘冈",
    101: "格勒诺布尔",
    102: "南锡",
    104: "红星",
    115: "索肖",
    433: "拉瓦勒",
    1297: "波城",
    1299: "布洛涅",
    1301: "罗德兹",
    1304: "敦刻尔克",
    3012: "阿纳西",
    # 荷甲
    193: "兹沃勒",
    194: "阿贾克斯",
    195: "威廉二世",
    196: "SBV精英",
    197: "埃因霍温",
    198: "海牙",
    201: "阿尔克马尔",
    202: "格罗宁根",
    205: "福图纳锡塔德",
    207: "乌德勒支",
    209: "费耶诺德",
    210: "海伦芬",
    410: "前进之鹰",
    413: "奈梅亨",
    415: "特温特",
    420: "坎布尔",
    426: "鹿特丹斯巴达",
    427: "特尔斯达",
    # 荷乙
    199: "格拉夫夏普",
    200: "维特斯",
    203: "布雷达NAC",
    204: "芬洛",
    206: "赫拉克勒斯",
    208: "埃门",
    409: "多德雷赫特",
    411: "埃因霍温青年队",
    412: "马斯特里赫特",
    414: "罗达JC",
    416: "沃伦丹",
    417: "瓦尔韦克",
    418: "阿尔克马尔青年队",
    419: "阿尔梅勒城",
    421: "邓博斯",
    422: "埃因霍温FC",
    423: "奥斯",
    424: "海尔蒙德体育",
    425: "阿贾克斯青年队",
    428: "乌德勒支青年队",
    # 葡超
    211: "本菲卡",
    212: "波尔图",
    214: "马里迪莫",
    215: "摩里伦斯",
    217: "布拉加",
    224: "吉马良斯",
    225: "马德拉国民",
    226: "里奥阿维",
    227: "圣克拉拉",
    228: "葡萄牙体育",
    230: "埃斯托里尔",
    238: "维塞乌学院",
    240: "阿罗卡",
    242: "法马利康",
    762: "吉尔维森特",
    4716: "卡萨皮亚",
    4724: "阿尔维卡",
    15130: "阿马多拉星队",
    # 苏超
    247: "凯尔特人",
    249: "希伯尼安",
    250: "基尔马诺克",
    251: "圣米伦",
    252: "阿伯丁",
    253: "邓迪",
    254: "哈茨",
    256: "马瑟韦尔",
    257: "流浪者",
    258: "圣约翰斯顿",
    1386: "邓迪联",
    1389: "福尔柯克",
    # 挪超
    319: "布兰",
    320: "克里斯蒂安松",
    321: "利勒斯特罗姆",
    325: "特罗姆瑟",
    326: "瓦勒伦加",
    327: "博德闪烁",
    329: "莫尔德",
    331: "罗森博格",
    332: "桑讷菲尤尔",
    333: "萨普斯堡08",
    334: "斯塔特",
    757: "奥勒松",
    759: "维京",
    2143: "奥斯陆KFUM",
    2149: "腓特烈斯塔",
    2159: "哈姆卡姆",
    # 瑞典超
    363: "哈马比",
    364: "佐加顿斯",
    366: "哥德堡",
    367: "哈肯",
    370: "天狼星",
    371: "布罗马波伊卡纳",
    372: "埃尔夫斯堡",
    374: "卡尔马",
    375: "马尔默",
    377: "AIK索尔纳",
    766: "哈尔姆斯塔德",
    2166: "厄格泰",
    2170: "盖斯",
    2172: "德格福什",
    2240: "米耶尔比",
    2241: "韦斯特罗斯",
    # 奥超及其他奥地利
    601: "奥地利维也纳",
    637: "格拉茨风暴",
    660: "瓦杜兹",
    781: "维也纳快速",
    # 比甲及其他比利时
    554: "安德莱赫特",
    631: "根特",
    1393: "圣吉罗斯联合",
    # 丹超及其他丹麦
    397: "中日德兰",
    398: "北西兰",
    400: "哥本哈根",
    # 瑞士超及其他瑞士
    606: "卢加诺",
    630: "锡永",
    1011: "圣加仑",
    1012: "图恩",
    # 希腊超及其他希腊
    553: "奥林匹亚科斯",
    617: "帕纳辛纳科斯",
    619: "塞萨洛尼基PAOK",
    # 土超及其他土耳其
    549: "贝西克塔斯",
    # 捷甲及其他捷克
    628: "布拉格斯巴达",
    1122: "亚布洛内茨",
    3723: "赫拉德茨克拉洛韦",
    # 欧陆其他俱乐部
    274: "雷克雅未克瓦鲁尔",
    275: "斯特亚尔南",
    278: "雷克雅未克维京人",
    354: "新圣徒",
    356: "卡那封镇",
    357: "康纳斯码头",
    388: "鲍里索夫BATE",
    394: "明斯克迪纳摩",
    556: "卡拉巴赫",
    559: "布加勒斯特星",
    561: "里耶卡",
    562: "阿斯塔纳",
    563: "贝尔谢巴工人",
    568: "蒂拉斯波尔警长",
    572: "基辅迪纳摩",
    573: "贝尔格莱德游击",
    574: "斯科普里瓦尔达尔",
    580: "戈塔维京人",
    582: "阿拉什克特",
    583: "林菲尔德",
    586: "维尔纽斯扎尔吉里斯",
    588: "莫斯塔尔日林斯基",
    591: "圣科洛马",
    598: "贝尔格莱德红星",
    602: "阿波罗利马索尔",
    604: "特拉维夫马卡比",
    608: "斯普利特海杜克",
    609: "什肯迪亚",
    614: "拉纳卡AEK",
    620: "萨格勒布迪纳摩",
    632: "克拉约瓦大学",
    648: "齐拉",
    649: "赫尔辛基",
    651: "费伦茨瓦罗斯",
    652: "沙姆洛克流浪",
    656: "布拉迪斯拉发斯拉夫人",
    657: "耶路撒冷贝塔",
    659: "瓦莱塔",
    661: "利耶帕亚",
    662: "诺姆卡柳",
    664: "阿拉木图凯拉特",
    667: "林肯红魔鬼",
    669: "科尔雷恩",
    670: "德里城",
    673: "苏捷斯卡",
    679: "萨拉热窝",
    682: "鲁纳维克",
    684: "迪弗当日",
    685: "库塔伊西鱼雷",
    687: "塔林弗洛拉",
    691: "奥尔黑米勒萨米",
    698: "圣约瑟夫",
    701: "克拉克斯维克",
    702: "伏伊伏丁那",
    709: "埃里温皮尤尼克",
    1120: "特尔纳瓦斯巴达克",
    1163: "伊尔维斯",
    1164: "图尔库国际",
    1165: "库普斯",
    1483: "瓦拉日丁",
    2036: "UNA斯特拉森",
    2037: "蒙多夫",
    2191: "佩尼邦特",
    2246: "克卢日",
    2249: "拉菲奥里塔",
    2257: "多瑙斯特雷达",
    2259: "托博尔",
    2260: "特雷菲奥里",
    2262: "第比利斯迪纳摩",
    2271: "彼得罗库布",
    2273: "塔林列瓦迪亚",
    2390: "帕克斯",
    2392: "德布勒森",
    2402: "吉奥利ETO",
    2599: "克卢日大学",
    3326: "地拉那迪纳摩",
    3327: "罗戈日纳埃格纳蒂亚",
    3339: "斯库台弗拉兹尼亚",
    3345: "埃斯卡尔德斯竞技",
    3364: "巴尼亚卢卡博拉茨",
    3381: "韦莱日",
    3403: "帕福斯",
    3484: "卡托维兹GKS",
    3491: "琴斯托霍瓦",
    3499: "迪拉",
    3502: "萨布尔塔洛",
    3528: "派德",
    3554: "日利纳",
    3683: "阿拉拉特亚美尼亚",
    3684: "诺亚",
    3740: "莫尔纳尔",
    3741: "彼得罗瓦茨",
    3745: "德契奇",
    3840: "波希米亚人",
    3854: "谢尔伯恩",
    3861: "黑格尔曼",
    3872: "考纳斯扎尔吉里斯",
    3874: "帕涅韦日斯",
    4133: "托尔斯港HB",
    4135: "奥达",
    4160: "里加FS",
    4165: "韦斯特里",
    4331: "西莱克斯",
    4358: "阿卢米尼",
    4359: "布拉沃",
    4360: "采列",
    4374: "科佩尔",
    4501: "特拉维夫夏普尔",
    4625: "弗洛里亚纳",
    4626: "哈姆伦斯巴达",
    4633: "基希讷乌野牛",
    5308: "维尔图斯",
    5352: "格伦托兰",
    5354: "拉恩",
    6496: "波利西亚",
    7808: "维捷布斯克ML",
    10124: "里加",
    10125: "欧罗巴",
    12733: "巴尔卡尼",
    13976: "沙巴赫",
    14281: "德里塔",
    14393: "杜卡吉尼",
    14507: "马尔萨什洛克",
    15576: "马利舍瓦",
    15847: "阿泰特比森",
    17161: "切尔卡瑟LNZ",
    18762: "利伯塔德",
    20406: "爱尔巴桑尼",
    21011: "塞梅伊叶利迈",
    # 巴甲
    118: "巴伊亚",
    119: "国际",
    120: "博塔弗戈",
    121: "帕尔梅拉斯",
    124: "弗鲁米嫩塞",
    126: "圣保罗",
    127: "弗拉门戈",
    128: "桑托斯",
    131: "科林蒂安",
    132: "沙佩科恩塞",
    133: "达伽马",
    134: "巴拉纳竞技",
    135: "克鲁塞罗",
    136: "维多利亚",
    147: "科里蒂巴",
    794: "布拉干蒂诺",
    1062: "米内罗竞技",
    1198: "雷莫",
    7848: "米拉索尔",
    # 阿甲
    434: "拉普拉塔体操",
    435: "河床",
    436: "竞技",
    437: "罗萨里奥中央",
    438: "萨斯菲尔德",
    440: "贝尔格拉诺",
    441: "圣菲联合",
    442: "防卫者正义",
    445: "飓风",
    446: "拉努斯",
    449: "班菲尔德",
    450: "拉普拉塔大学生",
    451: "博卡青年",
    452: "老虎",
    453: "独立",
    455: "图库曼竞技",
    456: "科尔多瓦高塔",
    457: "纽维尔老男孩",
    458: "阿根廷青年",
    460: "圣洛伦索",
    463: "阿尔多西维",
    473: "里瓦达维亚独立",
    474: "萨米恩托",
    476: "列斯特拉竞技",
    478: "科尔多瓦学院",
    1064: "普拉滕塞",
    1065: "圣地亚哥中央科尔多瓦",
    1066: "门多萨体操",
    2424: "里奥夸尔托大学生",
    2432: "巴拉卡斯中央",
    # 厄甲
    1148: "埃梅莱克",
    1149: "德尔芬",
    1151: "技术大学",
    1152: "瓜亚基尔巴塞罗那",
    1153: "独立山谷",
    1154: "昆卡体育",
    1155: "马卡拉",
    1156: "奥卡斯",
    1157: "天主教大学",
    1158: "基多大学",
    1159: "瓜亚基尔城",
    1162: "穆舒克鲁纳",
    1980: "曼塔FC",
    1992: "奥伦塞",
    19034: "北部雄狮",
    # 美职联
    1600: "休斯敦迪纳摩",
    1609: "新英格兰革命",
    1615: "华盛顿联",
    # 中超 / 中甲 / 中乙 / 中协杯
    830: "北京国安",
    833: "上海申花",
    834: "长春亚泰",
    836: "上海海港",
    837: "天津津门虎",
    838: "大连人",
    840: "河南",
    843: "广州",
    844: "山东泰山",
    848: "浙江",
    1431: "青岛海牛",
    5648: "成都蓉城",
    5684: "辽宁铁人",
    5686: "深圳新鹏城",
    5695: "武汉三镇",
    8351: "沧州雄狮",
    15784: "南通支云",
    17265: "青岛西海岸",
    21262: "重庆铜梁龙",
    21263: "大连英博",
    21265: "云南玉昆",
    21328: "兰州陇原竞技",
    23286: "陕西联合",
    27620: "大连可为",
    # 日职联
    281: "柏太阳神",
    282: "广岛三箭",
    283: "清水心跳",
    285: "长崎成功丸",
    287: "浦和红钻",
    288: "名古屋鲸八",
    289: "神户胜利船",
    290: "鹿岛鹿角",
    291: "大阪樱花",
    292: "东京FC",
    293: "大阪钢巴",
    294: "川崎前锋",
    296: "横滨水手",
    301: "千叶市原",
    302: "京都桑加",
    303: "町田泽维亚",
    305: "水户蜀葵",
    306: "东京绿茵",
    310: "冈山绿雉",
    316: "福冈黄蜂",
    # 韩K联
    2745: "富川1995",
    2746: "江原FC",
    2748: "安养FC",
    2750: "大田市民",
    2759: "光州FC",
    2761: "济州联",
    2762: "全北现代",
    2763: "仁川联",
    2764: "浦项制铁",
    2766: "首尔FC",
    2767: "蔚山HD",
    2768: "金泉尚武",
    # 保超及其他保加利亚
    566: "卢多戈雷茨",
    634: "普罗夫迪夫博特夫",
    646: "索菲亚列夫斯基",
    853: "索菲亚中央陆军",
    854: "索菲亚斯拉维亚",
    859: "弗拉察博特夫",
    1426: "索菲亚CSKA1948",
    4660: "瓦尔纳斯巴达克",
    # 阿根廷其他（阿乙 / 阿丁 / 业余杯）
    464: "全男孩",
    479: "胡胡伊体操",
    1931: "巴拉卡斯竞技",
    1942: "萨卡奇斯帕斯",
    1951: "中央北",
    1965: "特里斯坦苏亚雷斯",
    1967: "中央巴列斯特尔",
    8374: "凤凰",
    8391: "克莱波莱",
    8393: "穆尼斯竞技",
    8394: "巴拉圭竞技",
    23100: "贝里索之星",
    23104: "纳乌蒂科哈科阿赫",
    23105: "省队",
    23106: "SAT莫雷诺",
    27282: "罗萨里奥雄狮",
    # 巴西其他（乙丙 / 女足 / 州青年）
    138: "坎皮纳斯瓜拉尼",
    148: "隆德里纳",
    149: "帕伊桑杜",
    151: "戈亚斯",
    1794: "弗拉门戈女足",
    1802: "米内罗美洲女足",
    7772: "康菲安萨",
    7852: "阿纳波利斯",
    12973: "圣保罗U20",
    12987: "圣保罗博塔弗戈U20",
    13033: "诺沃里宗蒂诺U20",
    13034: "奥埃斯特U20",
    16497: "博塔弗戈女足",
    22833: "科英布拉U20",
    23157: "弗鲁米嫩塞女足",
    23643: "米内罗竞技U20",
    24473: "博塔弗戈U17",
    24482: "格雷米奥U17",
    # 智利
    2329: "意大利人体育",
    2335: "圣地亚哥晨报",
    2337: "纽布伦斯",
    18779: "圣华金雷亚尔",
    # 哥伦比亚
    1125: "百万富翁",
    1128: "麦德林独立",
    1129: "恩维加多",
    1135: "青年体育",
    1143: "雄狮FC",
    1144: "金鹰",
    1145: "老虎FC",
    1462: "佩雷拉竞技",
    1464: "平原人",
    15718: "布卡拉曼加女足",
    22099: "索阿查雷亚尔",
    25713: "翁斯卡尔达斯女足",
    # 巴拉圭 / 乌拉圭 / 委内瑞拉 / 巴拿马
    1179: "亚松森自由",
    1181: "卡瓦列罗将军",
    1187: "特里尼登塞",
    2138: "瓜伊雷尼亚",
    2355: "科洛尼亚广场",
    2359: "蒙得维的亚竞赛",
    2370: "马尔多纳多竞技",
    2371: "租户",
    2808: "加拉加斯",
    2813: "拉瓜伊拉竞技",
    2818: "梅里达大学生",
    2888: "大学竞技",
    2890: "拉乔雷拉独立",
    10474: "滕贝塔里竞技",
    10491: "塔夸里",
    16847: "苏利亚诺射线",
    # 墨西哥女足 / 哥斯达黎加
    821: "瓜达卢佩FC",
    14869: "华雷斯女足",
    14877: "莱昂女足",
    14884: "老虎女足",
    14885: "托卢卡女足",
    26343: "圣巴巴拉斗牛犬",
    # 北欧其他（挪甲以下 / 芬甲 / 冰岛 / 丹超补遗）
    271: "雷克雅未克KR",
    330: "奥德",
    365: "厄勒布鲁",
    405: "欧登塞",
    828: "奥拉夫斯维克维京古尔",
    1167: "罗瓦涅米",
    1171: "JJK于韦斯屈莱",
    2073: "锡尔克堡",
    2115: "塞尔福斯",
    2117: "雷克雅未克弗拉姆",
    2173: "诺尔比",
    2244: "TPV坦佩雷",
    6974: "贝鲁姆",
    6986: "弗拉姆",
    6996: "黑尔德",
    7012: "莫斯",
    7025: "谢滕",
    9189: "萨尔帕",
    9190: "坦佩雷联",
    9203: "中乌西马联",
    10113: "罗森博格二队",
    12891: "维京二队",
    16207: "利勒斯特罗姆二队",
    16219: "松达尔二队",
    16222: "奥勒松二队",
    16224: "兰海姆二队",
    18439: "海于格松二队",
    18518: "图尔库国际二队",
    18758: "库普斯学院",
    21349: "德勒巴克弗罗恩",
    21418: "桑纳菲尤尔二队",
    21420: "KFUM二队",
    22870: "阿斯科伊",
    22871: "奥萨内二队",
    25499: "林恩二队",
    27276: "奥斯特沃尔",
    # 英系及其他欧陆补遗
    344: "格丁尼亚阿尔卡",
    522: "巴勒莫",
    638: "特拉凯",
    857: "贝罗埃",
    953: "拉里萨",
    1085: "艾哈迈特",
    1357: "普利茅斯",
    1364: "埃克塞特城",
    1366: "哈特尔普尔",
    1409: "卢多戈雷茨二队",
    1415: "索菲亚中央陆军二队",
    1993: "火炬",
    2091: "特里卡拉",
    2110: "沃洛斯",
    2585: "圣格奥尔基塞普西",
    3518: "弗洛拉二队",
    3601: "彭迪克体育",
    3725: "普罗斯捷约夫",
    3871: "扎尔吉里斯二队",
    4138: "格罗比尼亚",
    4191: "斯卡拉",
    4197: "穆拉",
    4378: "拉多姆列",
    4659: "赫巴尔1918",
    5046: "卡拉马塔",
    6250: "波热加斯拉沃尼亚",
    6279: "BKMA埃里温",
    6807: "克万特",
    6823: "梁赞",
    6961: "斯基耶尔涅维采联合",
    7369: "乌尼乔夫",
    7370: "瓦拉什梅济里奇",
    7395: "巴特曼石油",
    7707: "卡舍尔顿竞技",
    7759: "温盖特芬奇利",
    8592: "久尔杰瓦茨边界",
    10168: "卢尼贾",
    10918: "林菲尔德女足",
    11910: "米德尔斯堡U21",
    13826: "诺梅卡柳二队",
    13971: "考纳斯扎尔吉里斯二队",
    14068: "胡门内",
    14075: "斯尼纳",
    17725: "圣彼得堡迪纳摩",
    18657: "拉阿格里",
    19689: "库日姆",
    21486: "克利夫顿维尔女足",
    22173: "弗利特伍德U21",
    23684: "坦佩尔",
    24848: "普雷斯顿U21",
    25403: "帕尔努蒸汽U21",
    27881: "十号FC",
    # 葡乙 / 葡U23
    229: "本菲卡B队",
    243: "波尔图B队",
    244: "莱绍埃斯",
    6358: "卢西塔尼亚劳罗萨",
    15464: "法马利康U23",
    15469: "布拉加U23",
    17474: "法鲁人U23",
    19824: "星队U23",
    21718: "维塞乌学院U23",
    21720: "托雷恩塞U23",
    # 澳大利亚 / 美职预备 / 韩女联
    945: "墨尔本城",
    948: "阿德莱德联",
    3786: "阿德莱德彗星",
    4025: "多伦多二队",
    4026: "奥兰多城二队",
    4040: "芝加哥火焰二队",
    10217: "雄狮",
    12866: "斯特特雄狮",
    14376: "华川KSPO女足",
    14377: "仁川红天使女足",
    15550: "麦克阿瑟",
    16777: "SD突袭者",
    18815: "纽约城二队",
    # 亚足联挑战联赛 / 亚冠补遗
    3542: "萨赫勒",
    3545: "海坦",
    4220: "帕赫塔科尔",
    4532: "侯赛因",
    8026: "多尔多伊比什凯克",
    8028: "航源",
    8044: "马齐亚",
    9118: "瓦斯巴",
    9426: "帕罗",
    12268: "雷加塔达兹",
    12543: "台南市",
    16400: "公安人民",
    16854: "乌兰巴托",
    20780: "福尔蒂斯",
    21167: "穆拉斯联",
    22067: "中央种马",
    26358: "阿布穆斯林",
    26629: "沙米亚",
    26631: "杰济拉",
    # 青年队 / U17 / U20
    12501: "澳大利亚U17",
    12516: "尼日利亚U17",
    19624: "巴林U20",
    19629: "阿曼U20",
    19630: "巴勒斯坦U20",
    21060: "塔吉克斯坦U20",
    21449: "中国U17",
    25822: "坦桑尼亚U17",
}

_BY_NAME_RAW: dict[str, str] = {
    # 国家队
    "Belgium": "比利时",
    "France": "法国",
    "Croatia": "克罗地亚",
    "Sweden": "瑞典",
    "Brazil": "巴西",
    "Uruguay": "乌拉圭",
    "Colombia": "哥伦比亚",
    "Spain": "西班牙",
    "England": "英格兰",
    "Panama": "巴拿马",
    "Japan": "日本",
    "Senegal": "塞内加尔",
    "Switzerland": "瑞士",
    "Mexico": "墨西哥",
    "South Korea": "韩国",
    "Australia": "澳大利亚",
    "Iran": "伊朗",
    "Saudi Arabia": "沙特阿拉伯",
    "Germany": "德国",
    "Argentina": "阿根廷",
    "Portugal": "葡萄牙",
    "Tunisia": "突尼斯",
    "Morocco": "摩洛哥",
    "Egypt": "埃及",
    "Czechia": "捷克",
    "Czech Republic": "捷克",
    "Austria": "奥地利",
    "Türkiye": "土耳其",
    "Turkey": "土耳其",
    "Norway": "挪威",
    "Scotland": "苏格兰",
    "Bosnia & Herzegovina": "波黑",
    "Bosnia and Herzegovina": "波黑",
    "Netherlands": "荷兰",
    "Ivory Coast": "科特迪瓦",
    "Côte d'Ivoire": "科特迪瓦",
    "Ghana": "加纳",
    "Ethiopia": "埃塞俄比亚",
    "Congo DR": "刚果（金）",
    "DR Congo": "刚果（金）",
    "South Africa": "南非",
    "Algeria": "阿尔及利亚",
    "Cape Verde Islands": "佛得角",
    "Cape Verde": "佛得角",
    "Vietnam": "越南",
    "Jordan": "约旦",
    "Iraq": "伊拉克",
    "Uzbekistan": "乌兹别克斯坦",
    "Qatar": "卡塔尔",
    "Paraguay": "巴拉圭",
    "Ecuador": "厄瓜多尔",
    "USA": "美国",
    "United States": "美国",
    "Haiti": "海地",
    "New Zealand": "新西兰",
    "Canada": "加拿大",
    "Curaçao": "库拉索",
    "Curacao": "库拉索",
    "Stjarnan": "斯特亚尔南",
    "Vikingur Reykjavik": "雷克雅未克维京人",
    "The New Saints": "新圣徒",
    "Caernarfon Town": "卡那封镇",
    "GAP Connah S Quay FC": "康纳斯码头",
    "Connah's Quay": "康纳斯码头",
    "Bate Borisov": "鲍里索夫BATE",
    "BATE Borisov": "鲍里索夫BATE",
    "Dinamo Minsk": "明斯克迪纳摩",
    "Qarabag": "卡拉巴赫",
    "FC Astana": "阿斯塔纳",
    "Sheriff Tiraspol": "蒂拉斯波尔警长",
    "Dynamo Kyiv": "基辅迪纳摩",
    "Vardar Skopje": "斯科普里瓦尔达尔",
    "Vikingur Gota": "戈塔维京人",
    "Alashkert": "阿拉什克特",
    "Linfield": "林菲尔德",
    "FK Zalgiris Vilnius": "维尔纽斯扎尔吉里斯",
    "FC Santa Coloma": "圣科洛马",
    "HNK Hajduk Split": "斯普利特海杜克",
    "Shkendija": "什肯迪亚",
    "Universitatea Craiova": "克拉约瓦大学",
    "Levski Sofia": "索菲亚列夫斯基",
    "Zira": "齐拉",
    "Ferencvarosi TC": "费伦茨瓦罗斯",
    "Shamrock Rovers": "沙姆洛克流浪",
    "FK Liepaja": "利耶帕亚",
    "Kalju Nomme": "诺姆卡柳",
    "Kairat Almaty": "阿拉木图凯拉特",
    "Lincoln Red Imps FC": "林肯红魔鬼",
    "Derry City": "德里城",
    "Sutjeska": "苏捷斯卡",
    "FK Sarajevo": "萨拉热窝",
    "NSI Runavik": "鲁纳维克",
    "FC Differdange 03": "迪弗当日",
    "Torpedo Kutaisi": "库塔伊西鱼雷",
    "Flora Tallinn": "塔林弗洛拉",
    "Milsami Orhei": "奥尔黑米勒萨米",
    "St Joseph S Fc": "圣约瑟夫",
    "KI Klaksvik": "克拉克斯维克",
    "Vojvodina": "伏伊伏丁那",
    "Pyunik Yerevan": "埃里温皮尤尼克",
    "CSKA Sofia": "索菲亚中央陆军",
    "CSKA 1948": "索菲亚CSKA1948",
    "Heart Of Midlothian": "哈茨",
    "Hearts": "哈茨",
    "Dinamo Zagreb": "萨格勒布迪纳摩",
    "FC Thun": "图恩",
    "Thun": "图恩",
    "Spartak Trnava": "特尔纳瓦斯巴达克",
    "Mjallby AIF": "米耶尔比",
    "Mjällby AIF": "米耶尔比",
    "Celje": "采列",
    "Bodo/Glimt": "博德闪烁",
    "Bodø/Glimt": "博德闪烁",
    "NEC Nijmegen": "奈梅亨",
    "NEC": "奈梅亨",
    "Olympiakos Piraeus": "奥林匹亚科斯",
    "Olympiacos": "奥林匹亚科斯",
    "Olympiacos Piraeus": "奥林匹亚科斯",
    "Hapoel Beer Sheva": "贝尔谢巴工人",
    "Hapoel Be'er Sheva": "贝尔谢巴工人",
    "FK Crvena Zvezda": "贝尔格莱德红星",
    "Crvena Zvezda": "贝尔格莱德红星",
    "Red Star Belgrade": "贝尔格莱德红星",
    "Sparta Praha": "布拉格斯巴达",
    "Sparta Prague": "布拉格斯巴达",
    "Slovan Bratislava": "布拉迪斯拉发斯拉夫人",
    "Union St. Gilloise": "圣吉罗斯联合",
    "Union Saint-Gilloise": "圣吉罗斯联合",
    "Royale Union Saint-Gilloise": "圣吉罗斯联合",
    "Ilves": "伊尔维斯",
    "Inter Turku": "图尔库国际",
    "KuPS": "库普斯",
    "DC United": "华盛顿联",
    "UNA Strassen": "UNA斯特拉森",
    "US Mondorf-les-bains": "蒙多夫",
    "Penybont": "佩尼邦特",
    "La Fiorita": "拉菲奥里塔",
    "Tre Fiori": "特雷菲奥里",
    "Dinamo Tbilisi": "第比利斯迪纳摩",
    "Petrocub": "彼得罗库布",
    "FC Levadia Tallinn": "塔林列瓦迪亚",
    "Gyori ETO FC": "吉奥利ETO",
    "Universitatea Cluj": "克卢日大学",
    "Dinamo Tirana": "地拉那迪纳摩",
    "Egnatia Rrogozhinë": "罗戈日纳埃格纳蒂亚",
    "Egnatia": "罗戈日纳埃格纳蒂亚",
    "Vllaznia Shkodër": "斯库台弗拉兹尼亚",
    "Atlètic Club d'Escaldes": "埃斯卡尔德斯竞技",
    "Atletic Club d'Escaldes": "埃斯卡尔德斯竞技",
    "Borac Banja Luka": "巴尼亚卢卡博拉茨",
    "Velež": "韦莱日",
    "Dila": "迪拉",
    "Saburtalo": "萨布尔塔洛",
    "Paide": "派德",
    "Žilina": "日利纳",
    "Zilina": "日利纳",
    "Ararat-Armenia": "阿拉拉特亚美尼亚",
    "Mornar": "莫尔纳尔",
    "Petrovac": "彼得罗瓦茨",
    "Dečić": "德契奇",
    "Bohemians": "波希米亚人",
    "Hegelmann Litauen": "黑格尔曼",
    "Kauno Žalgiris": "考纳斯扎尔吉里斯",
    "Kauno Zalgiris": "考纳斯扎尔吉里斯",
    "Rīgas FS": "里加FS",
    "Vestri": "韦斯特里",
    "Sileks": "西莱克斯",
    "Aluminij": "阿卢米尼",
    "Floriana": "弗洛里亚纳",
    "Hamrun Spartans": "哈姆伦斯巴达",
    "Virtus": "维尔图斯",
    "Glentoran": "格伦托兰",
    "Larne": "拉恩",
    "ML Vitebsk": "维捷布斯克ML",
    "Riga": "里加",
    "Europa": "欧罗巴",
    "Ballkani": "巴尔卡尼",
    "Sabah FA": "沙巴赫",
    "Drita": "德里塔",
    "Marsaxlokk": "马尔萨什洛克",
    "Malisheva": "马利舍瓦",
    "Atert Bissen": "阿泰特比森",
    "Libertad": "利伯塔德",
    "AF Elbasani": "爱尔巴桑尼",
    "Yelimay Semey": "塞梅伊叶利迈",
    # 英超
    "Manchester City": "曼城",
    "Manchester United": "曼联",
    "Liverpool": "利物浦",
    "Arsenal": "阿森纳",
    "Chelsea": "切尔西",
    "Tottenham": "热刺",
    "Tottenham Hotspur": "热刺",
    "Newcastle": "纽卡斯尔",
    "Newcastle United": "纽卡斯尔",
    "Aston Villa": "阿斯顿维拉",
    "West Ham": "西汉姆联",
    "West Ham United": "西汉姆联",
    "Brighton": "布莱顿",
    "Brighton and Hove Albion": "布莱顿",
    "Crystal Palace": "水晶宫",
    "Everton": "埃弗顿",
    "Fulham": "富勒姆",
    "Brentford": "布伦特福德",
    "Bournemouth": "伯恩茅斯",
    "Wolves": "狼队",
    "Wolverhampton Wanderers": "狼队",
    "Nottingham Forest": "诺丁汉森林",
    "Leicester": "莱斯特城",
    "Leicester City": "莱斯特城",
    "Southampton": "南安普顿",
    "Ipswich": "伊普斯维奇",
    "Ipswich Town": "伊普斯维奇",
    "Leeds": "利兹联",
    "Leeds United": "利兹联",
    "Burnley": "伯恩利",
    "Sunderland": "桑德兰",
    # 西甲
    "Barcelona": "巴萨",
    "FC Barcelona": "巴塞罗那",
    "Barca": "巴萨",
    "Real Madrid": "皇马",
    "Real Madrid CF": "皇家马德里",
    "Atletico Madrid": "马竞",
    "Atlético Madrid": "马竞",
    "Atleti": "马竞",
    "Athletic Club": "毕尔巴鄂",
    "Athletic Bilbao": "毕尔巴鄂",
    "Real Sociedad": "皇家社会",
    "Real Betis": "贝蒂斯",
    "Villarreal": "维拉利尔",
    "Sevilla": "塞维利亚",
    "Valencia": "瓦伦西亚",
    "Girona": "赫罗纳",
    "Osasuna": "奥萨苏纳",
    "Celta": "塞尔塔",
    "Celta Vigo": "塞尔塔",
    "Rayo Vallecano": "巴列卡诺",
    "Mallorca": "马略卡",
    "Getafe": "赫塔费",
    "Espanyol": "西班牙人",
    "Alaves": "阿拉维斯",
    "Deportivo Alaves": "阿拉维斯",
    "Leganes": "莱加内斯",
    "Las Palmas": "拉斯帕尔马斯",
    "Valladolid": "巴拉多利德",
    "Cadiz": "加的斯",
    "Granada CF": "格拉纳达",
    "Elche": "埃尔切",
    "Levante": "莱万特",
    # 德甲
    "Bayern": "拜仁",
    "Bayern Munich": "拜仁慕尼黑",
    "Bayern München": "拜仁慕尼黑",
    "Dortmund": "多特",
    "Borussia Dortmund": "多特蒙德",
    "Leipzig": "莱比锡",
    "RB Leipzig": "莱比锡红牛",
    "Leverkusen": "勒沃库森",
    "Bayer Leverkusen": "勒沃库森",
    "Frankfurt": "法兰克福",
    "Eintracht Frankfurt": "法兰克福",
    "Stuttgart": "斯图加特",
    "VfB Stuttgart": "斯图加特",
    "Gladbach": "门兴",
    "Borussia Monchengladbach": "门兴格拉德巴赫",
    "Borussia M.Gladbach": "门兴格拉德巴赫",
    "Wolfsburg": "沃尔夫斯堡",
    "Freiburg": "弗赖堡",
    "SC Freiburg": "弗赖堡",
    "Hoffenheim": "霍芬海姆",
    "Augsburg": "奥格斯堡",
    "FC Augsburg": "奥格斯堡",
    "Mainz": "美因茨",
    "Mainz 05": "美因茨",
    "FSV Mainz 05": "美因茨",
    "Union Berlin": "柏林联合",
    "Bremen": "不莱梅",
    "Werder Bremen": "云达不莱梅",
    "Koln": "科隆",
    "FC Koln": "科隆",
    "1.FC Köln": "科隆",
    "Bochum": "波鸿",
    "Heidenheim": "海登海姆",
    "St. Pauli": "圣保利",
    "Holstein Kiel": "霍尔施泰因基尔",
    "Hertha": "赫塔",
    "Hertha Berlin": "柏林赫塔",
    "Schalke": "沙尔克",
    "Schalke 04": "沙尔克04",
    # 意甲
    "Inter Milan": "国际米兰",
    "Milan": "AC米兰",
    "AC Milan": "AC米兰",
    "Juve": "尤文",
    "Juventus": "尤文",
    "Napoli": "那不勒斯",
    "AS Roma": "罗马",
    "Roma": "罗马",
    "Lazio": "拉齐奥",
    "Atalanta": "亚特兰大",
    "Fiorentina": "佛罗伦萨",
    "Bologna": "博洛尼亚",
    "Torino": "都灵",
    "Udinese": "乌迪内斯",
    "Genoa": "热那亚",
    "Cagliari": "卡利亚里",
    "Lecce": "莱切",
    "Empoli": "恩波利",
    "Verona": "维罗纳",
    "Hellas Verona": "维罗纳",
    "Monza": "蒙扎",
    "Sassuolo": "萨索洛",
    "Parma": "帕尔马",
    "Como": "科莫",
    "Venezia": "威尼斯",
    "Cremonese": "克雷莫纳",
    # 法甲
    "PSG": "巴黎",
    "Paris": "巴黎",
    "Paris Saint Germain": "巴黎圣日耳曼",
    "Paris Saint-Germain": "巴黎圣日耳曼",
    "Marseille": "马赛",
    "Olympique Marseille": "马赛",
    "OM": "马赛",
    "Monaco": "摩纳哥",
    "Lyon": "里昂",
    "Olympique Lyonnais": "里昂",
    "OL": "里昂",
    "Lille": "里尔",
    "Nice": "尼斯",
    "Rennes": "雷恩",
    "Lens": "朗斯",
    "Strasbourg": "斯特拉斯堡",
    "Nantes": "南特",
    "Toulouse": "图卢兹",
    "Brest": "布雷斯特",
    "Reims": "兰斯",
    "Montpellier": "蒙彼利埃",
    "Le Havre": "勒阿弗尔",
    "Angers": "昂热",
    "Auxerre": "欧塞尔",
    "Saint Etienne": "圣埃蒂安",
    "Saint-Etienne": "圣埃蒂安",
    "Metz": "梅斯",
    "Lorient": "洛里昂",
    "Clermont Foot": "克莱蒙",
    "Paris FC": "巴黎FC",
    # 日职联
    "Yokohama F. Marinos": "横滨水手",
    "Kashima": "鹿岛鹿角",
    "Kashima Antlers": "鹿岛鹿角",
    "Gamba Osaka": "大阪钢巴",
    "Urawa": "浦和红钻",
    "Urawa Reds": "浦和红钻",
    "Avispa Fukuoka": "福冈黄蜂",
    "Vissel Kobe": "神户胜利船",
    "Cerezo Osaka": "大阪樱花",
    "Fagiano Okayama": "冈山绿雉",
    "FC Tokyo": "东京FC",
    "Machida Zelvia": "町田泽维亚",
    "Kashiwa Reysol": "柏太阳神",
    "Mito Hollyhock": "水户蜀葵",
    "Nagoya Grampus": "名古屋鲸八",
    "Shimizu S-pulse": "清水心跳",
    "Sanfrecce Hiroshima": "广岛三箭",
    "JEF United Chiba": "千叶市原",
    "Tokyo Verdy": "东京绿茵",
    "Kawasaki Frontale": "川崎前锋",
    "V-varen Nagasaki": "长崎成功丸",
    "Kyoto Sanga": "京都桑加",
    # 葡超
    "Estoril": "埃斯托里尔",
    "Famalicao": "法马利康",
    "Maritimo": "马里迪莫",
    "Casa Pia": "卡萨皮亚",
    "Guimaraes": "吉马良斯",
    "Vitoria Guimaraes": "吉马良斯",
    "Arouca": "阿罗卡",
    "Estrela": "阿马多拉星队",
    "Estrela Amadora": "阿马多拉星队",
    "Sporting CP": "葡萄牙体育",
    "FC Porto": "波尔图",
    "Alverca": "阿尔维卡",
    "Academico Viseu": "维塞乌学院",
    "GIL Vicente": "吉尔维森特",
    "Gil Vicente": "吉尔维森特",
    "Rio Ave": "里奥阿维",
    "Moreirense": "摩里伦斯",
    "SC Braga": "布拉加",
    # 荷甲
    "Cambuur": "坎布尔",
    "Excelsior": "SBV精英",
    "GO Ahead Eagles": "前进之鹰",
    "Willem II": "威廉二世",
    "PSV Eindhoven": "埃因霍温",
    "Fortuna Sittard": "福图纳锡塔德",
    "AZ Alkmaar": "阿尔克马尔",
    "ADO Den Haag": "海牙",
    "Sparta Rotterdam": "鹿特丹斯巴达",
    "Feyenoord": "费耶诺德",
    "Groningen": "格罗宁根",
    "Utrecht": "乌德勒支",
    "PEC Zwolle": "兹沃勒",
    "Heerenveen": "海伦芬",
    "Telstar": "特尔斯达",
    # 挪超
    "Sandefjord": "桑讷菲尤尔",
    "KFUM Oslo": "奥斯陆KFUM",
    "Valerenga": "瓦勒伦加",
    "Sarpsborg 08 FF": "萨普斯堡08",
    "Sarpsborg 08": "萨普斯堡08",
    "Fredrikstad": "腓特烈斯塔",
    "Lillestrom": "利勒斯特罗姆",
    "Rosenborg": "罗森博格",
    "Ham-Kam": "哈姆卡姆",
    "Aalesund": "奥勒松",
    "Kristiansund BK": "克里斯蒂安松",
    "Molde": "莫尔德",
    # 阿甲
    "Lanus": "拉努斯",
    "Lanús": "拉努斯",
    "Union Santa Fe": "圣菲联合",
    "Unión Santa Fe": "圣菲联合",
    "Talleres Cordoba": "科尔多瓦高塔",
    "Talleres Córdoba": "科尔多瓦高塔",
    "Central Cordoba de Santiago": "圣地亚哥中央科尔多瓦",
    "Central Córdoba de Santiago": "圣地亚哥中央科尔多瓦",
    # 奥超及其他奥地利
    "Sturm Graz": "格拉茨风暴",
    "Rapid Vienna": "维也纳快速",
    "Austria Wien": "奥地利维也纳",
    "Salzburg": "萨尔茨堡红牛",
    "Red Bull Salzburg": "萨尔茨堡红牛",
    "LASK Linz": "林茨LASK",
    "Wolfsberger AC": "沃尔夫斯堡格AC",
    "Austria Klagenfurt": "克拉根福奥地利",
    "TSV Hartberg": "哈特贝格",
    "SCR Altach": "阿尔塔赫",
    "WSG Tirol": "蒂罗尔",
    "Grazer AK": "格拉茨AK",
    "Blau Weiss Linz": "林茨蓝白",
    "Ried": "里德",
    "SV Ried": "里德",
    # 中超 / 中甲 / 中乙 / 中协杯
    "Shandong Luneng": "山东泰山",
    "Shandong Taishan": "山东泰山",
    "Yunnan Yukun": "云南玉昆",
    "Beijing Guoan": "北京国安",
    "Shanghai Shenhua": "上海申花",
    "Shanghai Port": "上海海港",
    "Shanghai SIPG": "上海海港",
    "Henan Jianye": "河南",
    "Henan Songshan Longmen": "河南",
    "Hangzhou Greentown": "浙江",
    "Zhejiang Professional": "浙江",
    "Zhejiang": "浙江",
    "Wuhan Three Towns": "武汉三镇",
    "Chengdu Better City": "成都蓉城",
    "Chengdu Rongcheng": "成都蓉城",
    "Sichuan Jiuniu": "深圳新鹏城",
    "Shenzhen Xinpengcheng": "深圳新鹏城",
    "Qingdao Jonoon": "青岛海牛",
    "Qingdao Hainiu": "青岛海牛",
    "Qingdao Youth Island": "青岛西海岸",
    "Qingdao West Coast": "青岛西海岸",
    "Chongqing Tongliang Long": "重庆铜梁龙",
    "Tianjin Teda": "天津津门虎",
    "Tianjin Jinmen Tiger": "天津津门虎",
    "Changchun Yatai": "长春亚泰",
    "Meizhou Hakka": "梅州客家",
    "Cangzhou Mighty Lions": "沧州雄狮",
    "Nantong Zhiyun": "南通支云",
    "Shenyang Urban": "辽宁铁人",
    "Dalian Zhixing": "大连英博",
    "Rizhao Yuqi": "兰州陇原竞技",
    "Lanzhou Longyuan Athletic": "兰州陇原竞技",
    "Lanzhou Longyuan": "兰州陇原竞技",
    "Shaanxi Union": "陕西联合",
    "Dalian Kewei": "大连可为",
    # 韩K联
    "Bucheon FC 1995": "富川1995",
    "Gangwon FC": "江原FC",
    "FC Anyang": "安养FC",
    "Daejeon Citizen": "大田市民",
    "Gwangju FC": "光州FC",
    "Jeju United FC": "济州联",
    "Jeonbuk Motors": "全北现代",
    "Incheon United": "仁川联",
    "Pohang Steelers": "浦项制铁",
    "FC Seoul": "首尔FC",
    "Ulsan Hyundai FC": "蔚山HD",
    "Gimcheon Sangmu FC": "金泉尚武",
    # 厄甲
    "Emelec": "埃梅莱克",
    "Delfin SC": "德尔芬",
    "Tecnico Universitario": "技术大学",
    "Barcelona SC": "瓜亚基尔巴塞罗那",
    "Independiente del Valle": "独立山谷",
    "Deportivo Cuenca": "昆卡体育",
    "Macara": "马卡拉",
    "Aucas": "奥卡斯",
    "Universidad Catolica": "天主教大学",
    "LDU de Quito": "基多大学",
    "Guayaquil City FC": "瓜亚基尔城",
    "Mushuc Runa SC": "穆舒克鲁纳",
    "Manta FC": "曼塔FC",
    "Orense SC": "奥伦塞",
    "Leones del Norte": "北部雄狮",
    # 青年队 / U17 / U20
    "Australia U17": "澳大利亚U17",
    "Nigeria U17": "尼日利亚U17",
    "Bahrain U20": "巴林U20",
    "Oman U20": "阿曼U20",
    "Palestine U20": "巴勒斯坦U20",
    "Tajikistan U20": "塔吉克斯坦U20",
    "China PR U17": "中国U17",
    "Tanzania U17": "坦桑尼亚U17",
    # 欧陆及其他俱乐部别名
    "Ipswich Town FC": "伊普斯维奇",
    "Inter Club d'Escaldes": "埃斯卡尔德斯国际",
    "F91 Dudelange": "迪德朗日",
    "Penya Encarnada": "佩尼亚恩卡纳达",
    "Pas de la Casa": "帕斯德拉卡萨",
    "La Massana": "拉马萨纳",
}

BY_NAME: dict[str, str] = {k.lower(): v for k, v in _BY_NAME_RAW.items()}


def name_has_cjk(text: str | None) -> bool:
    """True when the string already contains Chinese characters."""
    if not text:
        return False
    return any("\u4e00" <= ch <= "\u9fff" for ch in str(text))


def persist_auto_names(updates: dict[int, str]) -> int:
    """Merge auto translations into memory + ``data/team_names_auto.json``.

    Curated ``BY_ID`` entries are never overwritten here. Returns how many ids
    were newly stored or changed in the auto map.
    """
    if not updates:
        return 0
    changed = 0
    for tid, zh in updates.items():
        text = str(zh or "").strip()
        if tid <= 0 or not text or tid in BY_ID:
            continue
        if AUTO_BY_ID.get(tid) == text:
            continue
        AUTO_BY_ID[tid] = text
        changed += 1
    if not changed:
        return 0
    _DATA_DIR.mkdir(parents=True, exist_ok=True)
    payload = {str(k): v for k, v in sorted(AUTO_BY_ID.items())}
    AUTO_NAMES_PATH.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return changed


def team_name_zh(name: str | None, team_id: int | None = None) -> str:
    """Resolve Chinese display name; fall back to original / empty."""
    if team_id is not None:
        try:
            tid = int(team_id)
        except (TypeError, ValueError):
            tid = None
        if tid is not None and tid in BY_ID:
            return BY_ID[tid]
        if tid is not None and tid in AUTO_BY_ID:
            return AUTO_BY_ID[tid]
    if not name:
        return ""
    trimmed = str(name).strip()
    hit = BY_NAME.get(trimmed.lower())
    if hit:
        return hit
    return trimmed


def team_needs_zh(name: str | None, team_id: int | None = None) -> bool:
    """True when resolved display name still has no Chinese characters."""
    return not name_has_cjk(team_name_zh(name, team_id))


def localize_match_teams(match: dict[str, Any]) -> dict[str, Any]:
    """Rewrite home/away labels on a form/H2H match row (in place + return)."""
    home_id = match.get("home_id")
    away_id = match.get("away_id")
    try:
        hid = int(home_id) if home_id is not None else None
    except (TypeError, ValueError):
        hid = None
    try:
        aid = int(away_id) if away_id is not None else None
    except (TypeError, ValueError):
        aid = None
    home = match.get("home")
    away = match.get("away")
    if home is not None or hid is not None:
        match["home"] = team_name_zh(home if isinstance(home, str) else None, hid) or home
    if away is not None or aid is not None:
        match["away"] = team_name_zh(away if isinstance(away, str) else None, aid) or away
    return match


async def backfill_team_names(session: Any) -> int:
    """Rewrite ``teams.name`` for every row that has a Chinese mapping.

    Returns the number of rows changed. Call after fixture sync so historical
    English rows become reusable Chinese names without waiting for re-fetch.
    """
    from sqlalchemy import select

    from app.models.team import Team

    rows = (await session.execute(select(Team))).scalars().all()
    updated = 0
    for team in rows:
        zh = team_name_zh(team.name, team.id)
        if zh and zh != team.name:
            team.name = zh
            updated += 1
    if updated:
        await session.commit()
    return updated
