/**
 * Club / national-team Chinese display names.
 * Prefer API-Sports team id; fall back to English name match.
 * Unmapped names are returned as-is (can extend this map over time).
 */
const BY_ID: Record<number, string> = {
  1: '比利时',
  2: '法国',
  9: '西班牙',
  31: '摩洛哥',
  275: '斯特亚尔南',
  356: '卡那封镇',
  394: '明斯克迪纳摩',
  556: '卡拉巴赫',
  562: '阿斯塔纳',
  568: '蒂拉斯波尔警长',
  572: '基辅迪纳摩',
  580: '戈塔维京人',
  582: '阿拉什克特',
  583: '林菲尔德',
  586: '维尔纽斯扎尔吉里斯',
  591: '圣科洛马',
  608: '斯普利特海杜克',
  609: '什肯迪亚',
  651: '费伦茨瓦罗斯',
  661: '利耶帕亚',
  662: '诺姆卡柳',
  670: '德里城',
  679: '萨拉热窝',
  682: '鲁纳维克',
  691: '奥尔黑米勒萨米',
  698: '圣约瑟夫',
  702: '伏伊伏丁那',
  709: '埃里温皮尤尼克',
  853: '索菲亚中央陆军',
  1164: '图尔库国际',
  2037: '蒙多夫',
  2191: '佩尼邦特',
  2262: '第比利斯迪纳摩',
  2273: '塔林弗洛拉列瓦迪亚',
  2599: '克卢日大学',
  3326: '地拉那迪纳摩',
  3339: '斯库台弗拉兹尼亚',
  3345: '埃斯卡尔德斯竞技',
  3381: '韦莱日',
  3499: '迪拉',
  3528: '派德',
  3554: '日利纳',
  3740: '莫尔纳尔',
  3741: '彼得罗瓦茨',
  3745: '德契奇',
  3840: '波希米亚人',
  3861: '黑格尔曼',
  4160: '里加FS',
  4165: '韦斯特里',
  4331: '西莱克斯',
  4358: '阿卢米尼',
  4626: '哈姆伦斯巴达',
  5308: '维尔图斯',
  5352: '格伦托兰',
  10125: '欧罗巴',
  14507: '马尔萨什洛克',
  15576: '马利舍瓦',
  21011: '塞梅伊叶利迈',
  // Common big clubs (for form/h2h opponents that may appear)
  33: '曼联',
  34: '纽卡斯尔',
  40: '利物浦',
  42: '阿森纳',
  47: '热刺',
  49: '切尔西',
  50: '曼城',
  529: '巴塞罗那',
  541: '皇家马德里',
  157: '拜仁慕尼黑',
  165: '多特蒙德',
  489: 'AC米兰',
  505: '国际米兰',
  496: '尤文图斯',
  85: '巴黎圣日耳曼',
}

const BY_NAME: Record<string, string> = Object.fromEntries(
  Object.entries({
    Belgium: '比利时',
    France: '法国',
    Spain: '西班牙',
    Morocco: '摩洛哥',
    Stjarnan: '斯特亚尔南',
    'Caernarfon Town': '卡那封镇',
    'Dinamo Minsk': '明斯克迪纳摩',
    Qarabag: '卡拉巴赫',
    'FC Astana': '阿斯塔纳',
    'Sheriff Tiraspol': '蒂拉斯波尔警长',
    'Dynamo Kyiv': '基辅迪纳摩',
    'Vikingur Gota': '戈塔维京人',
    Alashkert: '阿拉什克特',
    Linfield: '林菲尔德',
    'FK Zalgiris Vilnius': '维尔纽斯扎尔吉里斯',
    'FC Santa Coloma': '圣科洛马',
    'HNK Hajduk Split': '斯普利特海杜克',
    Shkendija: '什肯迪亚',
    'Ferencvarosi TC': '费伦茨瓦罗斯',
    'FK Liepaja': '利耶帕亚',
    'Kalju Nomme': '诺姆卡柳',
    'Derry City': '德里城',
    'FK Sarajevo': '萨拉热窝',
    'NSI Runavik': '鲁纳维克',
    'Milsami Orhei': '奥尔黑米勒萨米',
    'St Joseph S Fc': '圣约瑟夫',
    Vojvodina: '伏伊伏丁那',
    'Pyunik Yerevan': '埃里温皮尤尼克',
    'CSKA Sofia': '索菲亚中央陆军',
    'Inter Turku': '图尔库国际',
    'US Mondorf-les-bains': '蒙多夫',
    Penybont: '佩尼邦特',
    'Dinamo Tbilisi': '第比利斯迪纳摩',
    'FC Levadia Tallinn': '塔林列瓦迪亚',
    'Universitatea Cluj': '克卢日大学',
    'Dinamo Tirana': '地拉那迪纳摩',
    "Vllaznia Shkodër": '斯库台弗拉兹尼亚',
    "Atlètic Club d'Escaldes": '埃斯卡尔德斯竞技',
    "Atletic Club d'Escaldes": '埃斯卡尔德斯竞技',
    Velež: '韦莱日',
    Dila: '迪拉',
    Paide: '派德',
    Žilina: '日利纳',
    Mornar: '莫尔纳尔',
    Petrovac: '彼得罗瓦茨',
    Dečić: '德契奇',
    Bohemians: '波希米亚人',
    'Hegelmann Litauen': '黑格尔曼',
    'Rīgas FS': '里加FS',
    Vestri: '韦斯特里',
    Sileks: '西莱克斯',
    Aluminij: '阿卢米尼',
    'Hamrun Spartans': '哈姆伦斯巴达',
    Virtus: '维尔图斯',
    Glentoran: '格伦托兰',
    Europa: '欧罗巴',
    Marsaxlokk: '马尔萨什洛克',
    Malisheva: '马利舍瓦',
    'Yelimay Semey': '塞梅伊叶利迈',
    'Manchester City': '曼城',
    Liverpool: '利物浦',
    Arsenal: '阿森纳',
    Chelsea: '切尔西',
    'Manchester United': '曼联',
    Tottenham: '热刺',
    Barcelona: '巴塞罗那',
    'Real Madrid': '皇家马德里',
    Bayern: '拜仁慕尼黑',
    'Bayern München': '拜仁慕尼黑',
    'Bayern Munich': '拜仁慕尼黑',
    'Paris Saint Germain': '巴黎圣日耳曼',
    "Inter Club d'Escaldes": '埃斯卡尔德斯国际',
    'F91 Dudelange': '迪德朗日',
    'Penya Encarnada': '佩尼亚恩卡纳达',
    'Pas de la Casa': '帕斯德拉卡萨',
    'La Massana': '拉马萨纳',
  }).map(([k, v]) => [k.toLowerCase(), v]),
)

export function teamNameZh(
  name: string | null | undefined,
  teamId?: number | null,
): string {
  if (teamId != null && BY_ID[teamId]) return BY_ID[teamId]
  if (!name) return '—'
  const hit = BY_NAME[name.trim().toLowerCase()]
  if (hit) return hit
  // Partial contains match for form opponents with slight name variants
  const lower = name.trim().toLowerCase()
  for (const [en, zh] of Object.entries(BY_NAME)) {
    if (lower.includes(en) || en.includes(lower)) return zh
  }
  return name
}
